spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-service
      auto-offset-reset: earliest

      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.aman.paymentservice
        spring.json.value.default.type: com.aman.paymentservice.event.ReservationCreatedEvent

server:
  port: 8082
