

spring:
  application:
    name: reservation-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: reservation-service
      auto-offset-reset: earliest

      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.aman.reservationservice
        spring.json.value.default.type: com.aman.reservationservice.event.ReservationCreatedEvent

server:
  port: 8081
